rotulos = {
  "adj": {
        "EPI": "Emenda Parlamentar Impositivas",
        "GAB": "Gabinete",
        "SAAS": "Secretaria Adjunta de Administração Sistêmica",
        "SAEX": "Secretaria Adjunta Executiva",
        "SAGE": "Secretaria Adjunta de Gestão Educacional",
        "SAGP": "Secretaria Adjunta de Gestão de Pessoas",
        "SAGR": "Secretaria Adjunta de Gestão Regional",
        "SAIP": "Secretaria Adjunta de Infraestrutura e Patrimônio",
        "SARC": "Secretaria Adjunta de Regime de Colaboração"
      },
  "paoe": {
        "2009": "2009 - Manutenção de ações de informática",
        "2010": "2010 - Manutenção de órgãos colegiados",
        "2014": "2014 - Publicidade institucional e propaganda",
        "2284": "2284 - Manutenção do Conselho Estadual de Educação - CEE",
        "2895": "2895 - Alimentação Escolar da Educação de Jovens e Adultos",
        "2897": "2897 - Alimentação Escolar da Educação Especial",
        "2898": "2898 - Alimentação Escolar do Ensino Fundamental",
        "2899": "2899 - Alimentação Escolar do Ensino Médio",
        "2900": "2900 - Desenvolvimento da Educação de Jovens e Adultos",
        "2936": "2936 - Desenvolvimento das Modalidades de Ensino",
        "2957": "2957 - Desenvolvimento da Educação Especial",
        "4172": "4172 - Desenvolvimento do Ensino Fundamental",
        "4173": "4173 - Infraestrutura do Ensino Fundamental",
        "4174": "4174 - Desenvolvimento do Ensino Médio",
        "4175": "4175 - Infraestrutura da Educação de Jovens e Adultos",
        "4177": "4177 - Infraestrutura do Ensino Médio",
        "4178": "4178 - Infraestrutura da Educação Especial",
        "4179": "4179 - Transporte Escolar da Educação Especial",
        "4180": "4180 - Infraestrutura de Administração e Gestão",
        "4181": "4181 - Transporte Escolar do Ensino Fundamental",
        "4182": "4182 - Transporte Escolar do Ensino Médio",
        "4491": "4491 - Pagamento de verbas indenizatórias a servidores estaduais",
        "4524": "4524 - FMTE - Ensino Fundamental",
        "4525": "4525 - FMTE - Educação Infantil",
        "8002": "8002 - Recolhimento do PIS-PASEP e pagamento do abono",
        "8003": "8003 - Cumprimento de sentenças judiciais transitadas em julgado - Adm. Direta",
        "8026": "8026 - Pagamento de emendas parlamentares impositivas",
        "8040": "8040 - Recolhimento de encargos e obrigações previdenciárias de inativos e pensionistas do Estado de Mato Grosso"
},
  "macro": {
        "ACESSO_E_PERM": "ACESSO E PERMANÊNCIA",
        "AVALIAÇÃO": "AVALIAÇÃO",
        "CULTURA_DE_PAZ": "PROMOÇÃO DA CULTURA DE PAZ",
        "CURRÍCULO_AMPLIADO": "CURRÍCULO AMPLIADO",
        "DESENV_EDUCACIONAL": "DESENVOLVIMENTO EDUCACIONAL",
        "EPI": "EMENDA PARLAMENTAR IMPOSITIVAS",
        "EQUIDADE_DIVERSID": "EQUIDADE E DIVERSIDADE",
        "GESTÃO_INOVAÇÃO": "GESTÃO E INOVAÇÃO",
        "INFRAESTRUTURA": "INFRAESTRUTURA ESCOLAR",
        "REGIME_COLABORAÇÃO": "REGIME DE COLABORAÇÃO",
        "VALORIZAÇÃO_PRO": "VALORIZAÇÃO PROFISSIONAL"
    },
  "pilar": {
        "EPI": "Emenda Parlamentar Impositivas",
        "P_EQUIDADE_": "II - Equidade e Diversidade",
        "P_GESTÃO_": "V - Gestão para Resultados",
        "P_IMPACTO_": "I - Impacto Educacional",
        "P_INFRAESTR_": "IV - Infraestrutura",
        "P_TECNOLOGIA_": "III - Tecnologia e Educação",
        "P_VALORIZ_PRO": "VI - Valorização Profissional"
    },
  "eixo": {
        "E_ALFABETIZAÇÃO": "ALFABETIZAÇÃO",
        "E_ALIMENTAÇÃO_": "ALIMENTAÇÃO ESCOLAR",
        "E_ALTAS_HABILIDADES": "SUPERDOTAÇÃO E ALTAS HABILIDADES",
        "E_AVALIAÇÃO": "AVALIAÇÃO",
        "E_BEM-ESTAR_ESCOLAR": "BEM-ESTAR ESCOLAR",
        "E_BUSCA_ATIVA": "BUSCA ATIVA",
        "E_CULTURA_DE_PAZ": "PROMOÇÃO DA CULTURA DE PAZ",
        "E_DISTÚRBIOS_APRENDIZAGEM": "DISTÚRBIOS DE APRENDIZAGEM",
        "E_EDUC_EJA": "EDUCAÇÃO DE JOVENS E ADULTOS",
        "E_EDUC_CAMPO": "EDUCAÇÃO DO CAMPO",
        "E_EDUC_ESPECIAL": "EDUCAÇÃO ESPECIAL",
        "E_EDUC_INDÍGENA": "EDUCAÇÃO INDÍGENA",
        "E_EDUC_PROF_TEC": "EDUCAÇÃO PROFISSIONAL E TECNOLÓGICA",
        "E_EDUC_QUILOMBOLA": "EDUCAÇÃO QUILOMBOLA",
        "E_ENSINO_FUNDAMENTAL": "ENSINO FUNDAMENTAL",
        "E_ENSINO_MÉDIO": "ENSINO MÉDIO",
        "E_ESCOLA_TEMPO_INTEG": "ESCOLAS DE TEMPO INTEGRAL",
        "E_ESCOLAS_MILITARES": "ESCOLAS MILITARES",
        "E_FORMAÇÃO_DE_PROF": "FORMAÇÃO CONTINUADA DE PROFESSORES",
        "E_GESTÃO_DE_PESSOAS": "GESTÃO ESTRATÉGICA DE PESSOAS",
        "E_GESTÃO_DO_PATRIM": "GESTÃO DO PATRIMÔNIO",
        "E_GESTÃO_ESCOLAR": "GESTÃO ESCOLAR",
        "E_GESTÃO_INTEGRADA": "GESTÃO INTEGRADA",
        "E_IMIGRANTES": "IMIGRANTES",
        "E_INFRAESTRUTURA_ESC": "INFRAESTRUTURA ESCOLAR",
        "E_LÍNG_ESTRANGEIRAS": "LÍNGUAS ESTRANGEIRAS",
        "E_MATERIAIS_UNIFORM": "MATERIAIS E UNIFORMES ESCOLARES",
        "E_PROJ_PED_INTEGRAD": "PROJETOS PEDAGÓGICOS INTEGRADOS",
        "E_REGIME_COLABORAÇÃO": "REGIME DE COLABORAÇÃO",
        "E_SISTEMA_ESTRUT": "SISTEMA ESTRUTURADO DE ENSINO",
        "E_TECNOL_AMB_ESCOLAR": "TECNOLOGIA NO AMBIENTE ESCOLAR",
        "E_TRANSPORTE_ESCOLAR": "TRANSPORTE ESCOLAR",
        "E_VALORIZAÇÃO_PROF": "VALORIZAÇÃO PROFISSIONAL",
        "EPI": "EMENDA PARLAMENTAR IMPOSITIVAS"
    },
  "politica": {
        "_SISTEMA_ESTRUT": "Política Pública de Sistema Estruturado de Ensino",
        "_ALFABETIZAÇÃO": "Política Pública de Alfabetização",
        "_ED_TEMPO_INTEGR": "Política Pública de Educação em Tempo Integral",
        "_ESCOLAS_MILITAR": "Política Pública de Escolas Militares",
        "_NOVO_ENSINO_MÉD": "Política Pública de Novo Ensino Médio e Ensino Técnico Profissionalizante",
        "_LÍNGUAS_ESTRANG": "Política Pública de Línguas Estrangeiras",
        "_EDUC_INDÍGENA": "Política Pública de Educação Escolar Indígena",
        "_EDUC_QUILOMBOLA": "Política Pública de Educação Escolar Quilombola",
        "_EDUC_CAMPO": "Política Pública de Educação Escolar do Campo",
        "_EDUC_EJA": "Política Pública de Educação para Jovens e Adultos (EJA)",
        "_EDUC_ESPECIAL": "Política Pública de Educação Especial",
        "_PROJ_PED_INTEGR": "Política Pública de Projetos Pedagógicos Integrados",
        "_TECNOLOGIA_ESC": "Política Pública de Tecnologia no Ambiente Escolar",
        "_AVALIAÇÃO_MT": "Política Pública de Avaliação (Avalia MT)",
        "_ACESSO_E_PERM": "Política Pública de Acesso e Permanência",
        "_UNIFORMES_": "Política Pública de Uniformes Escolares",
        "_MATERIAIS_": "Política Pública de Materiais Escolares",
        "_ALIMENTAÇÃO_": "Política Pública de Alimentação Escolar",
        "_BEM-ESTAR_": "Política Pública de Bem-Estar Escolar",
        "_GESTÃO_ESCOLAR": "Política Pública de Gestão Escolar",
        "_GESTÃO_INTEGR": "Política Pública de Gestão Integrada",
        "_REGIME_COLAB": "Política Pública de Regime de Colaboração",
        "_TRANSPORTE_": "Política Pública de Transporte Escolar",
        "_VALORIZ_PROF": "Política Pública de Valorização Profissional",
        "_FORMAÇÃO_PROF": "Política Pública de Formação Continuada de Professores",
        "_GESTÃO_PESSOAS": "Política Pública de Gestão Estratégica de Pessoas",
        "_INFRAESTRUTURA": "Política Pública de Infraestrutura Escolar",
        "_GESTÃO_PATRIM": "Política Pública de Gestão do Patrimônio",
        "EPI": "Emenda Parlamentar Impositivas"
    },
  "grupo": {
        "1": "1 - Pessoal e Encargos Sociais",
        "3": "3 - Outras Despesas Corrente",
        "4": "4 - Investimentos"
    },
  "subgrupo": {
        "A": "A - Despesas Obrigatórias",
        "B": "B - Essenciais à Manutenção da Unidade",
        "C": "C - Prioridades Estratégicas LDO",
        "D": "D - Essenciais Finalísticas",
        "E": "E - Projetos de Investimentos",
        "F": "F - Demais Ações e Projetos Finalísticos"
    },
  "fonte": {
        "15000000": "1.500.0000 - Recursos não vinculados de Impostos",
        "15001001": "1.500.1001 - Recursos destinados à Manutenção e Desenvolvimento do Ensino",
        "15010000": "1.501.0000 - Outros Recursos não Vinculados",
        "15010100": "1.501.0100 - Outros Recursos não vinculados destinados ao Tesouro",
        "15400000": "1.540.0000 - Transferência de recursos do FUNDEB desenvolvimento do Ensino",
        "15401070": "1.540.1070 - Transferência de recursos do FUNDEB Remuneração Educação Básica",
        "15500000": "1.550.0000 - Recursos da Contribuição ao Salário Educação",
        "15520000": "1.552.0000 - Transferências de Recursos do FNDE referente ao Programa Nacional de Alimentação Escolar (PNAE)",
        "15530000": "1.553.0000 - Transferências de Recursos do FNDE referente ao P. N. de Apoio ao Transporte Escolar (PNATE)",
        "15690000": "1.569.0000 - Outras Transferências de Recursos do FNDE",
        "15700000": "1.570.0000 - Transferências do Governo Federal ref. a Convênios e outros Repasses vinculados à Educação",
        "15740000": "1.574.0000 - Recursos de Operações de Crédito Educação"
    },
    "subfuncao": {
        "122": "122 - ADMINISTRAÇÃO GERAL",
        "126": "126 - TECNOLOGIA DA INFORMAÇÃO",
        "131": "131 - COMUNICACAO SOCIAL",
        "272": "272 - PREVIDENCIA DO REGIME ESTATUTARIO",
        "361": "361 - ENSINO FUNDAMENTAL",
        "362": "362 - ENSINO MEDIO",
        "365": "365 - EDUCACAO INFANTIL",
        "366": "366 - EDUCACAO DE JOVENS E ADULTOS",
        "367": "367 - EDUCACAO ESPECIAL",
        "845": "845 - OUTRAS TRANSFERÊNCIAS",
        "846": "846 - OUTROS ENCARGOS ESPECIAIS"
    },
    "regiao": {
        "R100":	"REGIÃO I - NOROESTE I",
        "R200":	"REGIÃO II - NORTE",
        "R300":	"REGIÃO III - NORDESTE",
        "R400":	"REGIÃO IV - LESTE",
        "R500":	"REGIÃO V - SUDESTE",
        "R600":	"REGIÃO VI - SUL",
        "R700":	"REGIÃO VII - SUDOESTE",
        "R800":	"REGIÃO VIII - OESTE",
        "R900":	"REGIÃO IX - CENTRO OESTE",
        "R1000":	"REGIÃO X - CENTRO",
        "R1100":	"REGIÃO XI - NOROESTE II",
        "R1200":	"REGIÃO XII - CENTRO NORTE",
        "R9900":	"ESTADO"
    },      
}
